apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:hrlCf8QYJ3aIwiPuHzR+BOe47YJiUPgivjZHDGx+uQ6hY6I7,iv:wJxHDPYRagYM4w+JuVcD+otQtw58roU75jUaSjCURvI=,tag:/BcX6BXGFSRZRkNI4fRBUw==,type:str]
    credentials.json: ENC[AES256_GCM,data:ImG/HayOizbyLtb66v+wsA/Trp9nDU48a1JrNZC4wZLhoV61BNq7KE7eedqlKki56xoE/oWpB/b8YxBfsfVWfTr5cHfDNmCx21y567phDv3ld9Jh8op4Ede99tMNYSeR+adyQS98wBbPCLZ7kb5GN4chrqc0SEkOt6f3gkjn/MFBQFYQHa3CIidaHIn7eo5C4UosSz/9GQ5Y15LX20kG9VkQpaUkMIhVsy2fXsa+FQ==,iv:FoZobldxRIZUKKqTPP0Q5Tx/6c3Pfjs1uv49A/qQWuM=,tag:BtQ1o2ymbjxVxXhTeDAdMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16jhnds0y2uqdh27ucarl3hlsd9unp43scz4g8zr65s683y9dayks55p7jt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTnpmYXViOGlXODQzejhV
            UTdzUFN6N1VSZDZ4UzkwYVR2Nkp6RDdRRVYwClJNSVdFYUVxdUNib1dKRm1sU3R3
            TEFHZkhPNUFPbzAwRUh1QnYvd3VvU2cKLS0tIEhTRHlwZUtaQXgrczZpTzdvQVlu
            QksyZXZRcEszem13R2hxVm8yS0pyT2cKiwSDodv4F3nwAy/7PmLK+dhMjusPSYzL
            39ibLnaNbUrhuikF4+qWujhswPRi9d1fFthbtU53GUc0Bmz+wQFTNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-28T05:02:53Z"
    mac: ENC[AES256_GCM,data:IptMI/SvDv51jBn8i1BfKCAgoxV6EAKrWcWfvEPc3hArdDaQtf75yn3PtL+90hBoxvSlh7FpalMCRBXVvl3qoXIazVtxepsLYdlhkZHqZj6Bt5880Rppy1HwmAeLdmCZlD3ecQY+C1O1G0dLNFNJekborQnw7QrqDmK0jy9m3ls=,iv:dyto6zG7k4IYiDwf58Q6BY0g4/GS90dNkgkPiBCMAac=,tag:+hQjglstt69fYRf/cUN57g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
